apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: products-service

  template:
    metadata:
      labels:
        app: products-service

    spec:
      containers:
      - name: products-service
        image: products-service:1.0
        imagePullPolicy: Never

        ports:
        - containerPort: 3002

---
apiVersion: v1
kind: Service

metadata:
  name: products-service

spec:
  selector:
    app: products-service

  ports:
  - port: 80
    targetPort: 3002

  type: NodePort
